# Bot Credentials Configuration Template
# Copy this file to bots.yaml and fill in your actual credentials
# NEVER commit the actual bots.yaml file to version control

bots:
  # Default bot (used when no specific bot is requested)
  default: "acme"
  
  # Bot configurations
  configs:
    acme:
      name: "Acme Bot"
      kore:
        bot_id: "your-acme-bot-id"
        client_id: "your-acme-client-id"
        client_secret: "your-acme-client-secret"
      
    # Add additional bots here
    # example:
    #   name: "Example Bot"
    #   kore:
    #     bot_id: "your-example-bot-id"
    #     client_id: "your-example-client-id"
    #     client_secret: "your-example-client-secret"