export interface AnalysisAggregation {
    totalSessions: number;
    transferCount: number;
    containedCount: number;
    transferRate: number;
    containmentRate: number;
    averageSessionLength: number;
    totalMessages: number;
    averageMessagesPerSession: number;
    intentBreakdown: Record<string, number>;
    transferReasonBreakdown: Record<string, number>;
    dropOffLocationBreakdown: Record<string, number>;
    allSessionNotes: string[];
    sampleTranscripts: Array<{
        sessionId: string;
        intent: string;
        outcome: string;
        messages: Array<{
            message: string;
            message_type: string;
            timestamp: string;
        }>;
    }>;
}
export declare const ANALYSIS_OVERVIEW_PROMPT = "\n## 1. Analysis Overview (~150-200 words)\nWrite a clear, engaging summary that kicks off the analysis report. Think of this as explaining your findings to a colleague who wants the big picture first:\n\n**Start with the basics (1-2 sentences, NO section heading)**\n- Tell us what you analyzed - how many conversations, over what timeframe, and how you did it\n- Keep it straightforward and skip the jargon\n- Do NOT include any section heading like \"Section 1:\" or \"Scope & Methodology\"\n\n**Share the key numbers and what people were asking about (1 paragraph, no bullets, NO section heading)**\n- Weave together the main performance numbers and what users were trying to accomplish\n- Use **bold formatting** for the important stats (transfer rate, containment rate, session length)\n- Mention the top 3-4 things people were asking the bot about, with percentages worked naturally into your sentences\n- Write this as a flowing paragraph - no bullet points here\n- Do NOT include any section heading like \"Section 2:\" or \"Key Performance Metrics\"\n\n**Highlight what stood out (bullet points OK, small heading only)**\n- Use the heading \"**What Stood Out**\" (using ## markdown for smaller heading)\n- Point out the most interesting patterns you found - both good and concerning\n- Use bullet points to list your observations, keeping each one conversational\n- Use *italics* only for specific numbers and key terms, not whole sentences\n- Include wins and challenges - give us the real picture\n\n**Keep it readable:**\n- NO section headings for the first two parts\n- Only use \"**What Stood Out**\" as a ## heading for the third part\n- Use **bold** for important numbers and stats\n- Use *italics* sparingly - just for emphasis on specific details\n- Keep paragraphs short and digestible (2-3 sentences max)\n- Write like you're talking to a smart colleague, not writing a formal report\n- Call it \"XO bot\" or \"bot\" throughout\n";
export declare const DETAILED_ANALYSIS_PROMPT = "\n## 2. Detailed Analysis (~600-800 words, thorough but readable)\nNow dive deeper into what the data is telling us. This is where you get to tell the full story behind the numbers - write this for people who need to understand what's really happening and what to do about it.\n\n**What to cover:**\n- **How the bot is really performing**: Look at the patterns in how users interact with the bot and what leads to success or frustration\n- **When things go well vs. when they don't**: Dig into what makes some conversations work while others end up getting transferred\n- **The user experience journey**: Walk through where people get stuck, where they drop off, and what that tells us about pain points\n- **Why transfers happen**: Get into the real reasons - not just the categories, but what's actually going wrong from the user's perspective\n- **What to do about it**: Give specific, practical suggestions that can actually be implemented\n- **Connect the dots**: Use the actual numbers and patterns you're seeing to back up your insights\n- **Expert insight**: Share your analysis like you're the go-to person who really understands how bots work\n\n**Make it readable:**\n- Write in flowing paragraphs that tell a story, not bullet-heavy lists\n- Use clear section headers (##, ###) to break things up\n- Use **bold** for the important insights and key numbers\n- Use *italics* for specific data points and key terms\n- Write substantial paragraphs (4-6 sentences) that really explore what's happening\n- Keep calling it \"XO bot\" or \"bot\" consistently\n- Give us enough detail to really understand the situation\n\n**Try this structure:**\n### How Users Actually Interact with the Bot\n[2-3 paragraphs that dig into the real patterns you're seeing - how people engage, what they're trying to accomplish, where things work well, and what the numbers tell us about user behavior. Include specific data points and trends.]\n\n### When Conversations Break Down\n[2-3 paragraphs exploring what leads to transfers - the user experience that causes problems, common failure points, and how different issues affect people's satisfaction. Look at the connection between where people drop off and why they need help.]\n\n### What We Can Do About It\n[2-3 paragraphs with practical recommendations that make sense based on what you found. Give context about what would have the biggest impact, how changes might improve containment rates, and what would make the biggest difference for users. Include both quick wins and longer-term improvements.]\n";
export declare const CONTAINMENT_SUGGESTION_PROMPT = "\n## 3. Top Improvement Suggestion (1 sentence, plain text only)\nGive us the one change that would make the biggest difference in keeping more conversations contained. Write this as one clear, actionable sentence:\n\n- **Be specific**: Point to actual patterns in the data, not generic advice  \n- **Use the numbers**: Reference the top transfer reasons, drop-off spots, or percentages you found\n- **Focus on impact**: Go after the improvement that would help the most people\n- **Keep it concise**: Should fit nicely in a card display (under 120 characters works best)\n- **Make it sound natural**: Write like you're giving advice to a colleague, not writing a manual\n- **Include the data**: Work in specific percentages or numbers when they help make the point\n- **Stay consistent**: Keep using \"XO bot\" or \"bot\" \n- **Plain text only**: Don't use any markdown formatting (*italics*, **bold**, etc.) since this displays as regular text\n\n**Good examples of what we're looking for:**\n- \"Fix the account verification flow to prevent the 34% of transfers caused by authentication problems\"\n- \"Add help prompts during billing questions to keep 28% more conversations from getting transferred\"  \n- \"Expand the bot's knowledge about technical issues to handle the 19% of sessions that currently need human help\"\n- \"Make policy number entry easier to stop 41% of authentication-related transfers\"\n";
export declare function createAnalysisPrompt(aggregation: AnalysisAggregation, sessions: Array<{
    start_time: string;
}>): string;
//# sourceMappingURL=analysis-prompts.d.ts.map